import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export async function getServerSideProps({res}: any) {
  function getRndInteger(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1) ) + min;
  }

  res.setHeader('Cache-Control', `public, s-maxage=900, stale-while-revalidate=300`);
  
  try {
    const response = await fetch(`https://api.coinlore.net/api/ticker/?id=${getRndInteger(80,90)}`);

    // let data = await response.text();
    const tokenJson = await response.json()
    const responseTokenName = tokenJson[0].name
    const responsePrice = tokenJson[0].price_usd
    
    return {
      props: {
        cryptoPrice: {
          name: responseTokenName,
          price: responsePrice
        }
      }, // will be passed to the page component as props
    }
  } catch (e) {
    return {
      props: {
        cryptoPrice: {
          name: 'No Name',
          price: 100
        }
      }, // will be passed to the page component as props// will be passed to the page component as props
    }
  }
}


export default function Home({ cryptoPrice }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CrptoCurrency Price</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Crypto Pricing of the Day
        </h1>
        <br />
        <br />
        <br />

        <div className={styles.grid}>
          <h2>Name: {cryptoPrice.name}</h2>
        </div>
        <div className={styles.grid}>
          <h3>Price: {cryptoPrice.price}</h3>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
